In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7], [8, 9, 10]])
print("a", type(a))
print(a)
print("\nb", type(b))
print(b)

c = np.matrix([[1, 2], [3, 4]])
d = np.matrix([[5, 6, 7], [8, 9, 10]])
print("\nc", type(c))
print(c)
print("\nd", type(d))
print(d)
print("\ndot product of two ndarray objects")
print(np.dot(a, b))
print("\ndot product of two matrix objects")
print(np.dot(c, d))


a <class 'numpy.ndarray'>
[[1 2]
 [3 4]]

b <class 'numpy.ndarray'>
[[ 5  6  7]
 [ 8  9 10]]

c <class 'numpy.matrix'>
[[1 2]
 [3 4]]

d <class 'numpy.matrix'>
[[ 5  6  7]
 [ 8  9 10]]

dot product of two ndarray objects
[[21 24 27]
 [47 54 61]]

dot product of two matrix objects
[[21 24 27]
 [47 54 61]]
